name: flicker
base: core22
version: '0.1'
summary: Screenshot hotkey listener

description: |
  Flicker is a lightweight screenshot utility that listens for global
  hotkeys and spawns a helper to capture the screen or windows.

grade: stable
confinement: strict

apps:
  flicker:
    command: usr/bin/python3 -m flicker.app
    daemon: simple
    plugs:
      - desktop
      - desktop-legacy
      - wayland
      - x11
      - home

parts:
  flicker:
    plugin: python
    source: ../../
    python-requirements: flicker/requirements.txt
